import os
import re
import secrets
import smtplib
from datetime import datetime, timedelta
from email.message import EmailMessage
from functools import wraps
from pathlib import Path

import mysql.connector
from dotenv import load_dotenv
from werkzeug.middleware.proxy_fix import ProxyFix
from flask import (
    Flask,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename


# ============================================================
# APPLICATION SETUP
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

load_dotenv(BASE_DIR / ".env")

app = Flask(__name__)

# Trust the reverse proxy used by Railway/other managed hosts so HTTPS
# URLs generated by url_for(..., _external=True) use the public scheme.
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_port=1)

app.secret_key = os.getenv("SECRET_KEY", "smartclean-development-secret-change-me")

# Secure cookies in production. Keep False for local HTTP development.
app.config["SESSION_COOKIE_SECURE"] = os.getenv("SESSION_COOKIE_SECURE", "true").lower() == "true"
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")

app.config["UPLOAD_FOLDER"] = str(
    BASE_DIR / "static" / "uploads"
)

app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024

Path(
    app.config["UPLOAD_FOLDER"]
).mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

DB_CONFIG = {
    # Railway MySQL variables are supported automatically. The DB_* names
    # remain supported for local XAMPP/MySQL development.
    "host": os.getenv("DB_HOST") or os.getenv("MYSQLHOST", "localhost"),
    "port": int(os.getenv("DB_PORT") or os.getenv("MYSQLPORT", "3306")),
    "user": os.getenv("DB_USER") or os.getenv("MYSQLUSER", "root"),
    "password": os.getenv("DB_PASSWORD") or os.getenv("MYSQLPASSWORD", ""),
    "database": os.getenv("DB_NAME") or os.getenv("MYSQLDATABASE", "smartclean"),
}


# ============================================================
# SMTP CONFIGURATION
# ============================================================

SMTP_HOST = os.getenv(
    "SMTP_HOST",
    "smtp.gmail.com"
)

SMTP_PORT = int(
    os.getenv("SMTP_PORT", "587")
)

SMTP_EMAIL = os.getenv(
    "SMTP_EMAIL",
    ""
)

SMTP_PASSWORD = os.getenv(
    "SMTP_PASSWORD",
    ""
)

MAIL_FROM_NAME = os.getenv(
    "MAIL_FROM_NAME",
    "SmartClean"
)

RESET_EXPIRY_MINUTES = int(
    os.getenv(
        "RESET_EXPIRY_MINUTES",
        "30"
    )
)


# ============================================================
# ROLE CONFIGURATION
# ============================================================

ROLE_TABLES = {

    "citizen": {
        "table": "citizens",
        "id": "citizen_id",
        "role_name": "Citizen"
    },

    "worker": {
        "table": "workers",
        "id": "worker_id",
        "role_name": "Field Worker"
    },

    "admin": {
        "table": "admins",
        "id": "admin_id",
        "role_name": "Administrator"
    }

}


# ============================================================
# COMPLAINT CATEGORY MAP
# ============================================================

CATEGORY_MAP = {

    "overflowing":
        "Overflowing Bins",

    "uncollected":
        "Uncollected Waste",

    "damaged":
        "Damaged Bin",

    "illegal":
        "Illegal Dumping",

    "other":
        "Others"

}


# ============================================================
# DATABASE FUNCTIONS
# ============================================================

def get_db_connection():

    return mysql.connector.connect(
        **DB_CONFIG
    )


def current_user():

    role = session.get("role")

    user_id = session.get("user_id")


    if role not in ROLE_TABLES:
        return None


    if not user_id:
        return None


    cfg = ROLE_TABLES[role]


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            f"""
            SELECT *
            FROM {cfg["table"]}
            WHERE {cfg["id"]}=%s
            """,
            (user_id,)
        )

        user = cur.fetchone()

        return user

    finally:

        cur.close()

        conn.close()


def user_from_email(role, email):

    if role not in ROLE_TABLES:
        return None


    cfg = ROLE_TABLES[role]


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            f"""
            SELECT *
            FROM {cfg["table"]}
            WHERE email=%s
            """,
            (email,)
        )

        return cur.fetchone()

    finally:

        cur.close()

        conn.close()


def user_from_id(role, user_id):

    if role not in ROLE_TABLES:
        return None


    cfg = ROLE_TABLES[role]


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            f"""
            SELECT *
            FROM {cfg["table"]}
            WHERE {cfg["id"]}=%s
            """,
            (user_id,)
        )

        return cur.fetchone()

    finally:

        cur.close()

        conn.close()


# ============================================================
# PASSWORD FUNCTIONS
# ============================================================

def validate_password(password):

    if not password:
        return False


    if len(password) < 6:
        return False


    if not any(
        character.isupper()
        for character in password
    ):
        return False


    if not any(
        character.isdigit()
        for character in password
    ):
        return False


    return True


def password_matches(
    stored,
    supplied
):

    if not stored:
        return False


    if stored.startswith(
        (
            "pbkdf2:",
            "scrypt:"
        )
    ):

        return check_password_hash(
            stored,
            supplied
        )


    return secrets.compare_digest(
        str(stored),
        str(supplied)
    )


# ============================================================
# WORKER ID
# ============================================================

def normalize_worker_id(value):

    value = str(
        value or ""
    ).strip().upper()


    if value.startswith("WRK-"):

        value = value[4:]


    if value.isdigit():

        return int(value)


    return None


# ============================================================
# ROLE DECORATOR
# ============================================================

def role_required(role):

    def decorator(function):

        @wraps(function)

        def wrapper(
            *args,
            **kwargs
        ):

            if session.get("role") != role:

                return redirect(
                    url_for(
                        f"{role}_login"
                    )
                )


            return function(
                *args,
                **kwargs
            )


        return wrapper

    return decorator


# ============================================================
# JSON ERROR
# ============================================================

def safe_json_error(
    message,
    status=400
):

    return jsonify(
        {
            "success": False,
            "message": message
        }
    ), status


# ============================================================
# EMAIL
# ============================================================

def send_email(
    to_email,
    subject,
    body
):

    if not SMTP_EMAIL or not SMTP_PASSWORD:

        raise RuntimeError(
            "SMTP is not configured. "
            "Add SMTP_EMAIL and SMTP_PASSWORD to .env"
        )


    message = EmailMessage()

    message["Subject"] = subject

    message["From"] = (
        f"{MAIL_FROM_NAME} <{SMTP_EMAIL}>"
    )

    message["To"] = to_email

    message.set_content(body)


    with smtplib.SMTP(
        SMTP_HOST,
        SMTP_PORT,
        timeout=20
    ) as smtp:

        smtp.ehlo()

        smtp.starttls()

        smtp.ehlo()

        smtp.login(
            SMTP_EMAIL,
            SMTP_PASSWORD
        )

        smtp.send_message(
            message
        )


# ============================================================
# TEMPORARY PASSWORD
# ============================================================

def generate_temporary_password(
    length=10
):

    alphabet = (
        "ABCDEFGHJKLMNPQRSTUVWXYZ"
        "abcdefghijkmnopqrstuvwxyz"
        "23456789@#"
    )


    while True:

        password = "".join(
            secrets.choice(alphabet)
            for _ in range(length)
        )


        if validate_password(password):

            return password


# ============================================================
# COMPLAINT ID
# ============================================================

def complaint_display_id(
    complaint_id
):

    return (
        f"CW-{int(complaint_id):04d}"
    )


def parse_complaint_id(raw):

    value = str(
        raw or ""
    ).strip().upper()


    if value.startswith("CW-"):

        value = value[3:]


    if value.startswith("SG-"):

        value = value[3:]


    if value.isdigit():

        return int(value)


    return None


# ============================================================
# HOME
# ============================================================

@app.route("/")
def home():

    return render_template(
        "index.html"
    )


# ============================================================
# GENERAL LOGIN
# ============================================================

@app.route("/login")
def login():

    return render_template(
        "login.html"
    )


# ============================================================
# REPORT ISSUE
# ============================================================

@app.route(
    "/report-issue",
    methods=["GET", "POST"]
)
def report_issue():
    if session.get("role") != "citizen":
        return redirect(url_for("citizen_login", next="/report-issue"))
    user=current_user()
    if not user:
        session.clear(); return redirect(url_for("citizen_login", next="/report-issue"))
    if request.method=="GET":
        return render_template("report-issue.html",user=user,form_data={})
    category=request.form.get("category","").strip()
    issue_type=CATEGORY_MAP.get(category,category)
    location=request.form.get("location","").strip()
    description=request.form.get("description","").strip()
    form_data={"name":request.form.get("name","").strip(),"email":request.form.get("email","").strip(),"category":category,"location":location,"description":description}
    if not issue_type or not location or not description:
        return render_template("report-issue.html",user=user,form_data=form_data,error="Please fill all required fields."),400
    photo_path=None; photo=request.files.get("photo")
    if photo and photo.filename:
        ext=Path(photo.filename).suffix.lower()
        if ext not in {".jpg",".jpeg",".png"}:
            return render_template("report-issue.html",user=user,form_data=form_data,error="Only JPG and PNG images are allowed."),400
        filename=f"{secrets.token_hex(12)}{ext}"; photo.save(Path(app.config["UPLOAD_FOLDER"])/filename); photo_path=f"uploads/{filename}"
    conn=get_db_connection(); cur=conn.cursor()
    try:
        cur.execute("""INSERT INTO complaints (citizen_id,issue_type,ward_number,street_number,description,photo_path,status)
                       VALUES (%s,%s,%s,%s,%s,%s,'Pending')""",
                    (user["citizen_id"],issue_type,user.get("ward_number") or 0,location,description,photo_path))
        complaint_id=cur.lastrowid; conn.commit()
    except Exception: conn.rollback(); raise
    finally: cur.close(); conn.close()
    cid=complaint_display_id(complaint_id)
    return render_template("report-issue.html",user=user,form_data={},success=True,complaint_id=cid,success_message=f"Complaint {cid} submitted successfully.")

@app.route("/track")
def track():

    return render_template(
        "track.html"
    )


# ============================================================
# RECENT COMPLAINTS
# ============================================================

@app.route(
    "/api/complaints/recent"
)
def api_recent_complaints():

    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                complaint_id,
                description,
                street_number,
                status
            FROM complaints
            ORDER BY complaint_id DESC
            LIMIT 10
            """
        )


        rows = cur.fetchall()


    finally:

        cur.close()

        conn.close()


    output = []


    for row in rows:

        description = (
            row["description"] or ""
        )


        if len(description) > 70:

            title = (
                description[:70]
                + "..."
            )

        else:

            title = description


        status = row["status"]


        if status in (
            "Resolved",
            "Completed"
        ):

            display_status = "Completed"

        elif status == "Assigned":

            display_status = "Assigned"

        else:

            display_status = status


        output.append(
            {
                "id":
                    complaint_display_id(
                        row["complaint_id"]
                    ),

                "title":
                    title,

                "location":
                    row["street_number"],

                "status":
                    display_status
            }
        )


    return jsonify(output)


# ============================================================
# TRACK COMPLAINT API
# ============================================================

@app.route(
    "/api/complaints/<raw_id>"
)
def api_track(raw_id):

    complaint_id = parse_complaint_id(
        raw_id
    )


    if complaint_id is None:

        return safe_json_error(
            "Invalid complaint ID.",
            400
        )


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                c.*,
                ci.name AS citizen_name,
                ca.worker_id,
                w.name AS worker_name,

                (
                    SELECT MAX(updated_at)
                    FROM complaint_updates cu
                    WHERE cu.complaint_id =
                          c.complaint_id
                ) AS last_updated

            FROM complaints c

            JOIN citizens ci
                ON ci.citizen_id =
                   c.citizen_id

            LEFT JOIN complaint_assignments ca
                ON ca.complaint_id =
                   c.complaint_id

            LEFT JOIN workers w
                ON w.worker_id =
                   ca.worker_id

            WHERE c.complaint_id=%s
            """,
            (complaint_id,)
        )


        row = cur.fetchone()


    finally:

        cur.close()

        conn.close()


    if not row:

        return safe_json_error(
            "Complaint not found.",
            404
        )


    status = row["status"]


    if status == "Pending":

        display_status = "Submitted"


    elif status == "In Progress":

        display_status = "In Progress"


    elif status == "Assigned":

        display_status = "Assigned"


    elif status in (
        "Resolved",
        "Completed"
    ):

        display_status = "Completed"


    else:

        display_status = status


    description = (
        row["description"] or ""
    )


    if len(description) > 70:

        title = (
            description[:70]
            + "..."
        )

    else:

        title = description


    return jsonify(
        {
            "success": True,

            "id":
                complaint_display_id(
                    complaint_id
                ),

            "title":
                title,

            "ward":
                f"Ward {row['ward_number']}",

            "filed":
                (
                    row["complaint_date"]
                    .strftime("%d %b %Y")
                    if row["complaint_date"]
                    else "-"
                ),

            "status":
                display_status,

            "location":
                row["street_number"],

            "worker":
                (
                    row["worker_name"]
                    or "Not yet assigned"
                ),

            "category":
                row["issue_type"],

            "updated":
                (
                    row["last_updated"]
                    .strftime(
                        "%d %b %Y %H:%M"
                    )
                    if row["last_updated"]
                    else
                    "Not updated yet"
                )
        }
    )


# ============================================================
# CITIZEN LOGIN
# ============================================================

@app.route(
    "/citizen-login",
    methods=["GET", "POST"]
)
def citizen_login():
    if request.method == "GET":
        return render_template("citizen-login.html", email=request.args.get("email",""), error=None)
    email=request.form.get("email","").strip()
    password=request.form.get("password","")
    remember=bool(request.form.get("remember"))
    next_url=request.form.get("next") or request.args.get("next")
    if not email or not password:
        return render_template("citizen-login.html", error="Email and password are required.", email=email),400
    user=user_from_email("citizen",email)
    if not user or not password_matches(user["password"],password):
        return render_template("citizen-login.html", error="Invalid email or password.", email=email),401
    if not str(user["password"]).startswith(("pbkdf2:","scrypt:")):
        conn=get_db_connection(); cur=conn.cursor()
        try:
            cur.execute("UPDATE citizens SET password=%s WHERE citizen_id=%s",(generate_password_hash(password),user["citizen_id"])); conn.commit()
        finally: cur.close(); conn.close()
    session.clear(); session.permanent=remember
    session["user_id"]=user["citizen_id"]; session["role"]="citizen"; session["user_type"]="citizen"
    session["user_name"]=user["name"]; session["email"]=user["email"]
    if next_url and next_url.startswith("/") and not next_url.startswith("//"):
        return redirect(next_url)
    return redirect(url_for("citizen_dashboard"))

@app.route(
    "/citizen-register",
    methods=["GET", "POST"]
)
def citizen_register():

    if request.method == "GET":

        return render_template(
            "citizen-register.html"
        )


    return register_citizen()


# ============================================================
# GENERAL REGISTER
# ============================================================

@app.route(
    "/register",
    methods=["GET", "POST"]
)
def register():

    if request.method == "GET":

        return render_template(
            "register.html"
        )


    return redirect(
        url_for(
            "citizen_register"
        )
    )


# ============================================================
# REGISTER CITIZEN
# ============================================================

def register_citizen():

    name = request.form.get(
        "name",
        ""
    ).strip()


    phone = request.form.get(
        "phone",
        ""
    ).strip()


    email = request.form.get(
        "email",
        ""
    ).strip()


    address = request.form.get(
        "address",
        ""
    ).strip()


    password = request.form.get(
        "password",
        ""
    ).strip()


    ward = (
        request.form.get("area")
        or request.form.get(
            "ward_number"
        )
        or 0
    )


    confirm = request.form.get(
        "confirmPassword",
        password
    )


    if password != confirm:

        return render_template(
            "citizen-register.html",
            error="Passwords do not match."
        ), 400


    if not validate_password(
        password
    ):

        return render_template(
            "citizen-register.html",
            error=(
                "Password must be at least "
                "6 characters and contain "
                "an uppercase letter and number."
            )
        ), 400


    try:

        ward_number = int(
            ward or 0
        )

    except (
        TypeError,
        ValueError
    ):

        ward_number = 0


    conn = None

    cur = None


    try:

        conn = get_db_connection()

        cur = conn.cursor()


        cur.execute(
            """
            INSERT INTO citizens
            (
                name,
                email,
                phone,
                password,
                address,
                ward_number
            )
            VALUES
            (
                %s,
                %s,
                %s,
                %s,
                %s,
                %s
            )
            """,
            (
                name,
                email,
                phone,
                generate_password_hash(
                    password
                ),
                address,
                ward_number
            )
        )


        conn.commit()


    except mysql.connector.Error as e:

        return render_template(
            "citizen-register.html",
            error=(
                f"Registration failed: "
                f"{e.msg}"
            )
        ), 400


    finally:

        if cur:
            cur.close()

        if conn:
            conn.close()


    return redirect(
        url_for(
            "citizen_login"
        )
    )


# ============================================================
# CITIZEN DASHBOARD
# ============================================================

@app.route(
    "/citizen-dashboard"
)
@role_required("citizen")
def citizen_dashboard():

    return render_template(
        "citizen-dashboard.html",
        user=current_user()
    )


# ============================================================
# CITIZEN PROFILE
# ============================================================

@app.route("/api/citizen/dashboard")
@role_required("citizen")
def api_citizen_dashboard():
    conn=get_db_connection(); cur=conn.cursor(dictionary=True); cid=session["user_id"]
    try:
        cur.execute("""SELECT COUNT(*) total,COALESCE(SUM(status='Pending'),0) pending,
                              COALESCE(SUM(status='Assigned'),0) assigned,
                              COALESCE(SUM(status='In Progress'),0) in_progress,
                              COALESCE(SUM(status='Resolved'),0) resolved
                       FROM complaints WHERE citizen_id=%s""",(cid,))
        stats=cur.fetchone() or {}
        cur.execute("""SELECT complaint_id,issue_type,street_number,complaint_date,status
                       FROM complaints WHERE citizen_id=%s ORDER BY complaint_id DESC LIMIT 10""",(cid,))
        rows=cur.fetchall()
    finally: cur.close(); conn.close()
    recent=[{"id":complaint_display_id(r["complaint_id"]),"issue_type":r["issue_type"] or "-","location":r["street_number"] or "-",
             "date":r["complaint_date"].strftime("%d %b %Y") if r["complaint_date"] else "-","status":r["status"] or "-"} for r in rows]
    return jsonify({"total":int(stats.get("total") or 0),"pending":int(stats.get("pending") or 0),
                    "assigned":int(stats.get("assigned") or 0),"in_progress":int(stats.get("in_progress") or 0),
                    "resolved":int(stats.get("resolved") or 0),"recent":recent})
@app.route(
    "/citizen-profile",
    methods=["GET", "POST"]
)
@role_required("citizen")
def citizen_profile():
    user=current_user()
    if not user:
        session.clear(); return redirect(url_for("citizen_login"))
    if request.method=="POST": return update_profile("citizen")
    conn=get_db_connection(); cur=conn.cursor(dictionary=True)
    try:
        cur.execute("""SELECT complaint_id,issue_type,street_number,complaint_date,status
                       FROM complaints WHERE citizen_id=%s ORDER BY complaint_id DESC""",(session["user_id"],))
        rows=cur.fetchall()
    finally: cur.close(); conn.close()
    complaints=[{"id":complaint_display_id(r["complaint_id"]),"issue_type":r["issue_type"] or "-",
                 "location":r["street_number"] or "-","date":r["complaint_date"].strftime("%d %b %Y") if r["complaint_date"] else "-",
                 "status":r["status"] or "-"} for r in rows]
    return render_template("citizen-profile.html",user=user,complaints=complaints)

@app.route(
    "/worker-login",
    methods=["GET", "POST"]
)
def worker_login():

    if request.method == "GET":

        return render_template(
            "worker-login.html"
        )


    data = (
        request.get_json(
            silent=True
        )
        or request.form
    )


    remember_me = bool(data.get("remember"))


    worker_id = normalize_worker_id(
        data.get("workerId")
    )


    password = data.get(
        "password",
        ""
    )


    if not worker_id or not password:

        return safe_json_error(
            "Worker ID and password are required.",
            400
        )


    user = user_from_id(
        "worker",
        worker_id
    )


    if (
        not user
        or not password_matches(
            user["password"],
            password
        )
    ):

        return safe_json_error(
            "Invalid Worker ID or password.",
            401
        )


    if not str(
        user["password"]
    ).startswith(
        (
            "pbkdf2:",
            "scrypt:"
        )
    ):

        conn = get_db_connection()

        cur = conn.cursor()


        try:

            cur.execute(
                """
                UPDATE workers
                SET password=%s
                WHERE worker_id=%s
                """,
                (
                    generate_password_hash(
                        password
                    ),
                    user["worker_id"]
                )
            )


            conn.commit()

        finally:

            cur.close()

            conn.close()


    session.clear()
    session.permanent = remember_me

    session["user_id"] = (
        user["worker_id"]
    )

    session["role"] = "worker"


    return jsonify(
        {
            "success": True,
            "message": "Login successful!"
        }
    )


# ============================================================
# WORKER REGISTER
# ============================================================

@app.route("/worker-register", methods=["GET", "POST"])
def worker_register():
    if request.method == "GET":
        return render_template("worker-register.html")

    name = request.form.get("name", "").strip()
    phone = request.form.get("phone", "").strip()
    email = request.form.get("email", "").strip()
    address = request.form.get("address", "").strip()
    password = request.form.get("password", "").strip()
    confirm_password = request.form.get(
        "confirmPassword",
        password
    )

    status = request.form.get(
        "status",
        "Available"
    )

    # Check password match
    if password != confirm_password:
        return render_template(
            "worker-register.html",
            error="Passwords do not match."
        ), 400

    # Check password strength
    if not validate_password(password):
        return render_template(
            "worker-register.html",
            error=(
                "Password must be at least 6 characters "
                "and contain an uppercase letter and number."
            )
        ), 400

    conn = None
    cur = None

    try:
        conn = get_db_connection()
        cur = conn.cursor()

        # Insert worker
        cur.execute(
            """
            INSERT INTO workers
            (
                name,
                phone,
                email,
                address,
                password,
                status
            )
            VALUES
            (
                %s,
                %s,
                %s,
                %s,
                %s,
                %s
            )
            """,
            (
                name,
                phone,
                email or None,
                address,
                generate_password_hash(password),
                status
            )
        )

        # Get the automatically generated Worker ID
        worker_id = cur.lastrowid

        conn.commit()

        # Convert 1 -> WRK-0001
        display_worker_id = f"WRK-{worker_id:04d}"

        # Show the generated ID on the registration page
        return render_template(
            "worker-register.html",
            registration_success=True,
            worker_id=display_worker_id,
            worker_name=name
        )

    except mysql.connector.Error as e:

        if conn:
            conn.rollback()

        return render_template(
            "worker-register.html",
            error=f"Registration failed: {e.msg}"
        ), 400

    finally:

        if cur:
            cur.close()

        if conn:
            conn.close()
# ============================================================
# WORKER DASHBOARD
# ============================================================

@app.route(
    "/worker-dashboard"
)
@role_required("worker")
def worker_dashboard():

    return render_template(
        "worker-dashboard.html",
        user=current_user()
    )


# ============================================================
# WORKER COMPLAINTS PAGE
# ============================================================

@app.route(
    "/worker-complaints"
)
@role_required("worker")
def worker_complaints():

    return render_template(
        "worker-complaints.html",
        user=current_user()
    )


# ============================================================
# WORKER REPORTS PAGE
# ============================================================

@app.route(
    "/worker-reports"
)
@role_required("worker")
def worker_reports():

    return render_template(
        "worker-reports.html",
        user=current_user()
    )


# ============================================================
# WORKER PROFILE
# ============================================================

@app.route(
    "/worker-profile",
    methods=["GET", "POST"]
)
@role_required("worker")
def worker_profile():

    if request.method == "POST":

        return update_profile(
            "worker"
        )


    return render_template(
        "worker-profile.html",
        user=current_user()
    )


# ============================================================
# WORKER COMPLAINTS API
# ============================================================

@app.route(
    "/api/worker/complaints"
)
@role_required("worker")
def api_worker_complaints():

    worker_id = session["user_id"]


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                c.complaint_id,
                c.issue_type,
                c.street_number,
                c.description,
                c.complaint_date,
                c.status,
                ci.name AS citizen_name

            FROM complaint_assignments ca

            JOIN complaints c
                ON c.complaint_id =
                   ca.complaint_id

            JOIN citizens ci
                ON ci.citizen_id =
                   c.citizen_id

            WHERE ca.worker_id=%s

            ORDER BY
                c.complaint_date DESC,
                c.complaint_id DESC
            """,
            (worker_id,)
        )


        rows = cur.fetchall()


    finally:

        cur.close()

        conn.close()


    for row in rows:

        row["id"] = (
            complaint_display_id(
                row["complaint_id"]
            )
        )


        row["date"] = (
            row["complaint_date"].strftime(
                "%d %b %Y"
            )
            if row["complaint_date"]
            else "-"
        )


    return jsonify(rows)


# ============================================================
# WORKER UPDATE COMPLAINT STATUS
# ============================================================

@app.route(
    "/api/worker/complaints/<raw_id>/status",
    methods=["POST"]
)
@role_required("worker")
def api_worker_update(raw_id):

    complaint_id = parse_complaint_id(
        raw_id
    )


    data = (
        request.get_json(
            silent=True
        )
        or request.form
    )


    new_status = data.get(
        "status"
    )


    allowed_statuses = {
        "In Progress",
        "Resolved"
    }

    if complaint_id is None or new_status not in allowed_statuses:
        return safe_json_error(
            "Invalid complaint or status. Use In Progress or Resolved.",
            400
        )


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                c.status

            FROM complaints c

            JOIN complaint_assignments ca
                ON ca.complaint_id =
                   c.complaint_id

            WHERE
                c.complaint_id=%s
                AND ca.worker_id=%s
            """,
            (
                complaint_id,
                session["user_id"]
            )
        )


        row = cur.fetchone()


        if not row:

            return safe_json_error(
                "Complaint is not assigned to you.",
                403
            )


        old_status = row["status"]

        # Enforce the Worker workflow:
        # Assigned -> In Progress -> Resolved
        valid_transition = (
            (old_status == "Assigned" and new_status == "In Progress")
            or (old_status == "In Progress" and new_status == "Resolved")
        )

        if not valid_transition:
            return safe_json_error(
                f"Invalid status transition: {old_status} -> {new_status}. "
                "Worker flow is Assigned -> In Progress -> Resolved.",
                400
            )

        cur.execute(
            """
            UPDATE complaints
            SET status=%s
            WHERE complaint_id=%s
            """,
            (new_status, complaint_id)
        )

        cur.execute(
            """
            UPDATE complaint_assignments
            SET assignment_status=%s
            WHERE
                complaint_id=%s
                AND worker_id=%s
            """,
            (
                new_status,
                complaint_id,
                session["user_id"]
            )
        )

        cur.execute(
            """
            INSERT INTO complaint_updates
            (
                complaint_id,
                updated_by,
                old_status,
                new_status,
                update_description
            )
            VALUES
            (
                %s,
                NULL,
                %s,
                %s,
                %s
            )
            """,
            (
                complaint_id,
                old_status,
                new_status,
                "Status updated by assigned worker"
            )
        )

        conn.commit()


    finally:

        cur.close()

        conn.close()


    return jsonify(
        {
            "success": True
        }
    )


# ============================================================
# WORKER DASHBOARD API
# ============================================================

@app.route(
    "/api/worker/dashboard"
)
@role_required("worker")
def api_worker_dashboard():

    worker_id = session["user_id"]


    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaint_assignments
            WHERE worker_id=%s
            """,
            (worker_id,)
        )

        assigned = cur.fetchone()["n"]


        cur.execute(
            """
            SELECT COUNT(*) AS n

            FROM complaint_assignments ca

            JOIN complaints c
                ON c.complaint_id =
                   ca.complaint_id

            WHERE
                ca.worker_id=%s
                AND c.status IN
                (
                    'Assigned',
                    'In Progress'
                )
            """,
            (worker_id,)
        )

        pending = cur.fetchone()["n"]


        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaint_assignments ca
            JOIN complaints c ON c.complaint_id=ca.complaint_id
            WHERE ca.worker_id=%s AND c.status='In Progress'
            """,
            (worker_id,)
        )
        in_progress = cur.fetchone()["n"]

        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaint_assignments ca
            JOIN complaints c ON c.complaint_id=ca.complaint_id
            WHERE ca.worker_id=%s AND c.status='Resolved'
            """,
            (worker_id,)
        )

        completed = cur.fetchone()["n"]

        cur.execute(
            """
            SELECT c.complaint_id,c.issue_type,c.status
            FROM complaint_assignments ca
            JOIN complaints c ON c.complaint_id=ca.complaint_id
            WHERE ca.worker_id=%s
            ORDER BY c.complaint_id DESC
            LIMIT 5
            """,
            (worker_id,)
        )
        recent = cur.fetchall()

        # Monthly statistics for the currently logged-in worker
        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaint_assignments
            WHERE worker_id=%s
              AND assigned_date >= DATE_FORMAT(CURDATE(), '%Y-%m-01')
              AND assigned_date < DATE_ADD(
                    DATE_FORMAT(CURDATE(), '%Y-%m-01'),
                    INTERVAL 1 MONTH
              )
            """,
            (worker_id,)
        )
        monthly_assigned = cur.fetchone()["n"]

        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaint_assignments ca
            JOIN complaints c
              ON c.complaint_id = ca.complaint_id
            WHERE ca.worker_id=%s
              AND ca.assigned_date >= DATE_FORMAT(CURDATE(), '%Y-%m-01')
              AND ca.assigned_date < DATE_ADD(
                    DATE_FORMAT(CURDATE(), '%Y-%m-01'),
                    INTERVAL 1 MONTH
              )
              AND c.status = 'Resolved'
            """,
            (worker_id,)
        )
        monthly_completed = cur.fetchone()["n"]

        monthly_efficiency = (
            round((monthly_completed / monthly_assigned) * 100)
            if monthly_assigned
            else 0
        )


    finally:

        cur.close()

        conn.close()


    return jsonify(
        {
            "assigned": assigned,
            "pending": pending,
            "in_progress": in_progress,
            "completed": completed,
            "recent": [
                {
                    "complaint_display_id": complaint_display_id(r["complaint_id"]),
                    "issue_type": r["issue_type"] or "-",
                    "status": r["status"] or "-"
                }
                for r in recent
            ],
            "monthly_assigned": monthly_assigned,
            "monthly_completed": monthly_completed,
            "monthly_efficiency": monthly_efficiency,
            "worker": current_user()
        }
    )


# ============================================================
# ADMIN LOGIN
# ============================================================

@app.route(
    "/admin-login",
    methods=["GET", "POST"]
)
def admin_login():

    if request.method == "GET":

        return render_template(
            "admin-login.html"
        )


    email = request.form.get(
        "email",
        ""
    ).strip()


    password = request.form.get(
        "password",
        ""
    )


    user = user_from_email(
        "admin",
        email
    )


    if (
        not user
        or not password_matches(
            user["password"],
            password
        )
    ):

        return render_template(
            "admin-login.html",
            error="Invalid admin credentials."
        ), 401


    if not str(
        user["password"]
    ).startswith(
        (
            "pbkdf2:",
            "scrypt:"
        )
    ):

        conn = get_db_connection()

        cur = conn.cursor()


        try:

            cur.execute(
                """
                UPDATE admins
                SET password=%s
                WHERE admin_id=%s
                """,
                (
                    generate_password_hash(
                        password
                    ),
                    user["admin_id"]
                )
            )


            conn.commit()

        finally:

            cur.close()

            conn.close()


    session.clear()
    session.permanent = bool(request.form.get("remember"))
    session["user_id"] = user["admin_id"]
    session["role"] = "admin"
    session["user_type"] = "admin"
    session["user_name"] = user["name"]
    session["email"] = user["email"]


    return redirect(
        url_for(
            "admin_dashboard"
        )
    )


# ============================================================
# ADMIN REGISTER
# ============================================================

@app.route(
    "/admin-register",
    methods=["GET", "POST"]
)
def admin_register():

    if request.method == "GET":

        return render_template(
            "admin-register.html"
        )


    name = request.form.get(
        "name",
        ""
    ).strip()


    phone = request.form.get(
        "phone",
        ""
    ).strip()


    email = request.form.get(
        "email",
        ""
    ).strip()


    # FIX: Get address from the registration form
    address = request.form.get(
        "address",
        ""
    ).strip()


    password = request.form.get(
        "password",
        ""
    ).strip()


    confirm = request.form.get(
        "confirmPassword",
        password
    )


    # Required field validation
    if not name:
        return render_template(
            "admin-register.html",
            error="Name is required."
        ), 400


    if not phone:
        return render_template(
            "admin-register.html",
            error="Phone number is required."
        ), 400


    if not email:
        return render_template(
            "admin-register.html",
            error="Email is required."
        ), 400


    if not password:
        return render_template(
            "admin-register.html",
            error="Password is required."
        ), 400


    if password != confirm:
        return render_template(
            "admin-register.html",
            error="Passwords do not match."
        ), 400


    if not validate_password(
        password
    ):
        return render_template(
            "admin-register.html",
            error=(
                "Password must be at least "
                "6 characters and contain "
                "an uppercase letter and number."
            )
        ), 400


    conn = None
    cur = None


    try:

        conn = get_db_connection()

        cur = conn.cursor()


        # Check whether email already exists
        cur.execute(
            """
            SELECT admin_id
            FROM admins
            WHERE email = %s
            """,
            (
                email,
            )
        )

        existing_email = cur.fetchone()


        if existing_email:

            return render_template(
                "admin-register.html",
                error=(
                    "An admin account with "
                    "this email already exists."
                )
            ), 400


        # Check whether phone already exists
        cur.execute(
            """
            SELECT admin_id
            FROM admins
            WHERE phone = %s
            """,
            (
                phone,
            )
        )

        existing_phone = cur.fetchone()


        if existing_phone:

            return render_template(
                "admin-register.html",
                error=(
                    "An admin account with "
                    "this phone number already exists."
                )
            ), 400


        # Insert new admin
        cur.execute(
            """
            INSERT INTO admins
            (
                name,
                email,
                password,
                phone,
                address
            )
            VALUES
            (
                %s,
                %s,
                %s,
                %s,
                %s
            )
            """,
            (
                name,
                email,
                generate_password_hash(
                    password
                ),
                phone,
                address
            )
        )


        conn.commit()


    except mysql.connector.Error as e:

        if conn:
            conn.rollback()


        return render_template(
            "admin-register.html",
            error=(
                f"Registration failed: "
                f"{e.msg}"
            )
        ), 400


    finally:

        if cur:
            cur.close()


        if conn:
            conn.close()


    return redirect(
        url_for(
            "admin_login"
        )
    )

# ============================================================
# ADMIN DASHBOARD
# ============================================================

@app.route(
    "/admin-dashboard"
)
@role_required("admin")
def admin_dashboard():

    return render_template(
        "admin-dashboard.html",
        user=current_user()
    )


# ============================================================
# ADMIN PROFILE
# ============================================================

@app.route(
    "/admin-profile",
    methods=["GET", "POST"]
)
@role_required("admin")
def admin_profile():

    if request.method == "POST":

        return update_profile(
            "admin"
        )


    return render_template(
        "admin-profile.html",
        user=current_user()
    )


# ============================================================
# ADMIN COMPLAINTS
# ============================================================

@app.route(
    "/admin-complaints"
)
@role_required("admin")
def admin_complaints():

    return render_template(
        "admin-complaints.html",
        user=current_user()
    )


# ============================================================
# ADMIN WORKERS
# ============================================================

@app.route(
    "/admin-workers",
    methods=["GET", "POST"]
)
@role_required("admin")
def admin_workers():

    if request.method == "POST":

        data = request.form


        password = data.get(
            "password",
            generate_temporary_password()
        )


        if not validate_password(
            password
        ):

            return render_template(
                "admin-workers.html",
                user=current_user(),
                error=(
                    "Worker password must "
                    "contain uppercase and "
                    "number and be at least "
                    "6 characters."
                )
            ), 400


        conn = None

        cur = None


        try:

            conn = get_db_connection()

            cur = conn.cursor()


            cur.execute(
                """
                INSERT INTO workers
                (
                    name,
                    phone,
                    email,
                    address,
                    password,
                    status
                )
                VALUES
                (
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s
                )
                """,
                (
                    data.get("name"),
                    data.get("phone"),
                    data.get("email")
                    or None,
                    data.get("address"),
                    generate_password_hash(
                        password
                    ),
                    data.get(
                        "status",
                        "Available"
                    )
                )
            )


            conn.commit()


        except mysql.connector.Error as e:

            return render_template(
                "admin-workers.html",
                user=current_user(),
                error=(
                    f"Could not add worker: "
                    f"{e.msg}"
                )
            ), 400


        finally:

            if cur:
                cur.close()

            if conn:
                conn.close()


    return render_template(
        "admin-workers.html",
        user=current_user()
    )


# ============================================================
# ADMIN REPORTS
# ============================================================

@app.route(
    "/admin-reports"
)
@role_required("admin")
def admin_reports():

    return render_template(
        "admin-reports.html",
        user=current_user()
    )


# ============================================================
# ADMIN STATS API
# ============================================================

@app.route(
    "/api/admin/stats"
)
@role_required("admin")
def api_admin_stats():

    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaints
            """
        )

        total = cur.fetchone()["n"]


        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaints
            WHERE status='Pending'
            """
        )

        pending = cur.fetchone()["n"]


        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM complaints
            WHERE status IN
            (
                'Resolved',
                'Completed'
            )
            """
        )

        resolved = cur.fetchone()["n"]


        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM workers
            WHERE status='Available'
            """
        )

        available_workers = (
            cur.fetchone()["n"]
        )


        cur.execute(
            """
            SELECT COUNT(*) AS n
            FROM workers
            """
        )

        worker_total = (
            cur.fetchone()["n"]
        )


    finally:

        cur.close()

        conn.close()


    return jsonify(
        {
            "total": total,
            "pending": pending,
            "resolved": resolved,
            "workers": worker_total,
            "available_workers":
                available_workers
        }
    )


# ============================================================
# ADMIN COMPLAINTS API
# ============================================================

@app.route(
    "/api/admin/complaints"
)
@role_required("admin")
def api_admin_complaints():

    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                c.*,
                ci.name AS citizen_name,
                w.name AS worker_name,
                ca.worker_id AS worker_id

            FROM complaints c

            JOIN citizens ci
                ON ci.citizen_id =
                   c.citizen_id

            LEFT JOIN complaint_assignments ca
                ON ca.complaint_id =
                   c.complaint_id

            LEFT JOIN workers w
                ON w.worker_id =
                   ca.worker_id

            ORDER BY
                c.complaint_id DESC
            """
        )


        rows = cur.fetchall()


    finally:

        cur.close()

        conn.close()


    for row in rows:

        row["id"] = (
            complaint_display_id(
                row["complaint_id"]
            )
        )


        row["date"] = (
            row["complaint_date"].strftime(
                "%d %b %Y"
            )
            if row["complaint_date"]
            else "-"
        )


        row["location"] = (
            row["street_number"]
        )


    return jsonify(rows)


# ============================================================
# ADMIN ASSIGN COMPLAINT
# ============================================================

@app.route(
    "/api/admin/complaints/<raw_id>/assign",
    methods=["POST"]
)
@role_required("admin")
def api_assign(raw_id):
    complaint_id=parse_complaint_id(raw_id)
    data=request.get_json(silent=True) or request.form
    worker_id=normalize_worker_id(data.get("worker_id"))
    if complaint_id is None or worker_id is None:
        return safe_json_error("Valid complaint and worker IDs are required.",400)
    conn=get_db_connection(); cur=conn.cursor(dictionary=True)
    try:
        cur.execute("SELECT worker_id FROM workers WHERE worker_id=%s",(worker_id,))
        if not cur.fetchone(): return safe_json_error("Worker not found.",404)
        cur.execute("SELECT complaint_id,status FROM complaints WHERE complaint_id=%s FOR UPDATE",(complaint_id,))
        complaint=cur.fetchone()
        if not complaint: return safe_json_error("Complaint not found.",404)
        old=complaint["status"]
        cur.execute("""SELECT assignment_id,worker_id FROM complaint_assignments
                       WHERE complaint_id=%s ORDER BY assignment_id DESC LIMIT 1""",(complaint_id,))
        existing=cur.fetchone()
        if existing:
            cur.execute("""UPDATE complaint_assignments SET worker_id=%s,assigned_date=CURRENT_TIMESTAMP,
                           assignment_status='Assigned' WHERE assignment_id=%s""",(worker_id,existing["assignment_id"]))
        else:
            cur.execute("""INSERT INTO complaint_assignments(complaint_id,worker_id,assigned_date,assignment_status)
                           VALUES(%s,%s,CURRENT_TIMESTAMP,'Assigned')""",(complaint_id,worker_id))
        cur.execute("UPDATE complaints SET status='Assigned' WHERE complaint_id=%s",(complaint_id,))
        if old!="Assigned" or not existing or existing["worker_id"]!=worker_id:
            cur.execute("""INSERT INTO complaint_updates(complaint_id,updated_by,old_status,new_status,update_description)
                           VALUES(%s,%s,%s,'Assigned',%s)""",(complaint_id,session["user_id"],old,f"Complaint assigned to worker WRK-{worker_id:04d}"))
        conn.commit()
    except Exception: conn.rollback(); raise
    finally: cur.close(); conn.close()
    return jsonify({"success":True,"message":f"Complaint {complaint_display_id(complaint_id)} assigned successfully."})

@app.route(
    "/api/admin/workers"
)
@role_required("admin")
def api_admin_workers():

    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                worker_id,
                name,
                phone,
                email,
                address,
                status,
                created_at

            FROM workers

            ORDER BY worker_id DESC
            """
        )


        rows = cur.fetchall()


    finally:

        cur.close()

        conn.close()


    for row in rows:

        row["display_id"] = (
            f"WRK-{row['worker_id']:04d}"
        )


        row["created_at"] = (
            row["created_at"].strftime(
                "%d %b %Y"
            )
            if row["created_at"]
            else "-"
        )


    return jsonify(rows)


# ============================================================
# ADMIN REPORTS API
# ============================================================

@app.route(
    "/api/admin/reports"
)
@role_required("admin")
def api_admin_reports():

    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT
                issue_type,
                COUNT(*) AS count

            FROM complaints

            GROUP BY issue_type

            ORDER BY count DESC
            """
        )


        categories = cur.fetchall()


        cur.execute(
            """
            SELECT
                status,
                COUNT(*) AS count

            FROM complaints

            GROUP BY status

            ORDER BY count DESC
            """
        )


        statuses = cur.fetchall()


    finally:

        cur.close()

        conn.close()


    return jsonify(
        {
            "categories": categories,
            "statuses": statuses
        }
    )


@app.route("/admin-reports/download")
@role_required("admin")
def admin_reports_download():
    import csv
    from io import StringIO
    conn=get_db_connection(); cur=conn.cursor(dictionary=True)
    try:
        cur.execute("""SELECT c.complaint_id,c.issue_type,c.ward_number,c.street_number,ci.name citizen_name,
                              c.complaint_date,c.status,w.name worker_name
                       FROM complaints c JOIN citizens ci ON ci.citizen_id=c.citizen_id
                       LEFT JOIN complaint_assignments ca ON ca.complaint_id=c.complaint_id
                       LEFT JOIN workers w ON w.worker_id=ca.worker_id ORDER BY c.complaint_id DESC""")
        rows=cur.fetchall()
    finally: cur.close(); conn.close()
    out=StringIO(); writer=csv.writer(out)
    writer.writerow(["Complaint ID","Issue Type","Ward","Location","Citizen","Date","Status","Worker"])
    for r in rows:
        writer.writerow([complaint_display_id(r["complaint_id"]),r["issue_type"] or "",r["ward_number"] or "",
                          r["street_number"] or "",r["citizen_name"] or "",r["complaint_date"].strftime("%Y-%m-%d") if r["complaint_date"] else "",
                          r["status"] or "",r["worker_name"] or "Not Assigned"])
    resp=app.response_class(out.getvalue(),mimetype="text/csv")
    resp.headers["Content-Disposition"]='attachment; filename="smartclean_complaints_report.csv"'
    return resp
# ============================================================
# WORKER REPORTS API
# ============================================================

@app.route(
    "/api/worker/reports"
)
@role_required("worker")
def api_worker_reports():

    worker_id = session["user_id"]

    conn = get_db_connection()
    cur = conn.cursor(dictionary=True)

    try:
        # Overall worker assignment statistics
        cur.execute(
            """
            SELECT
                COUNT(*) AS assigned,
                COALESCE(SUM(c.status = 'Resolved'), 0) AS resolved,
                COALESCE(SUM(c.status IN ('Assigned', 'In Progress')), 0) AS pending
            FROM complaint_assignments ca
            JOIN complaints c
                ON c.complaint_id = ca.complaint_id
            WHERE ca.worker_id=%s
            """,
            (worker_id,)
        )
        summary = cur.fetchone() or {}

        assigned = int(summary.get("assigned") or 0)
        resolved = int(summary.get("resolved") or 0)
        pending = int(summary.get("pending") or 0)
        efficiency = round((resolved / assigned) * 100) if assigned else 0

        # Waste-category breakdown for this worker's RESOLVED complaints.
        # issue_type is the category stored by the current database design.
        cur.execute(
            """
            SELECT
                c.issue_type AS category,
                COUNT(*) AS count
            FROM complaint_assignments ca
            JOIN complaints c
                ON c.complaint_id = ca.complaint_id
            WHERE ca.worker_id=%s
              AND c.status='Resolved'
            GROUP BY c.issue_type
            ORDER BY count DESC, c.issue_type ASC
            """,
            (worker_id,)
        )
        category_rows = cur.fetchall()

        resolved_total = sum(int(r["count"] or 0) for r in category_rows)
        categories = []
        for row in category_rows:
            count = int(row["count"] or 0)
            percentage = round((count / resolved_total) * 100, 1) if resolved_total else 0
            categories.append({
                "category": row["category"] or "Other",
                "count": count,
                "percentage": percentage
            })

        # Adjust rounding so displayed percentages total exactly 100 when data exists.
        if categories:
            rounded_total = sum(c["percentage"] for c in categories)
            difference = round(100 - rounded_total, 1)
            categories[0]["percentage"] = round(
                categories[0]["percentage"] + difference, 1
            )

        # Recent history for this worker only.
        cur.execute(
            """
            SELECT
                c.complaint_id,
                c.issue_type,
                c.street_number,
                c.complaint_date,
                c.status
            FROM complaint_assignments ca
            JOIN complaints c
                ON c.complaint_id = ca.complaint_id
            WHERE ca.worker_id=%s
            ORDER BY c.complaint_date DESC, c.complaint_id DESC
            LIMIT 20
            """,
            (worker_id,)
        )
        history_rows = cur.fetchall()

    finally:
        cur.close()
        conn.close()

    history = []
    for row in history_rows:
        history.append({
            "id": complaint_display_id(row["complaint_id"]),
            "issue_type": row["issue_type"] or "-",
            "location": row["street_number"] or "-",
            "date": (
                row["complaint_date"].strftime("%d %b %Y")
                if row["complaint_date"]
                else "-"
            ),
            "status": row["status"] or "-"
        })

    return jsonify({
        "assigned": assigned,
        "resolved": resolved,
        "completed": resolved,
        "pending": pending,
        "efficiency": efficiency,
        "rating": None,
        "categories": categories,
        "history": history
    })


# ============================================================
# FORGOT PASSWORD
# ============================================================

def ensure_password_resets_table():

    conn = get_db_connection()
    cur = conn.cursor()

    try:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS password_resets (
                reset_id INT PRIMARY KEY AUTO_INCREMENT,
                email VARCHAR(100) NOT NULL,
                user_type ENUM('citizen','worker','admin') NOT NULL,
                token VARCHAR(255) NOT NULL UNIQUE,
                expires_at DATETIME NOT NULL,
                used BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                INDEX idx_reset_email (email),
                INDEX idx_reset_expiry (expires_at)
            )
            """
        )
        conn.commit()
    finally:
        cur.close()
        conn.close()

@app.route(
    "/forgot-password",
    methods=["GET", "POST"]
)
def forgot_password():

    if request.method == "GET":

        role = request.args.get(
            "role",
            "citizen"
        )

    else:

        role = request.form.get(
            "role",
            "citizen"
        )


    if role not in ROLE_TABLES:

        role = "citizen"


    if request.method == "GET":

        return render_template(
            "forgot-password.html",
            role=role
        )


    email = request.form.get(
        "email",
        ""
    ).strip()


    try:
        ensure_password_resets_table()
    except Exception as e:
        return render_template(
            "forgot-password.html",
            role=role,
            error=(
                "Unable to prepare password reset. "
                f"({e})"
            )
        ), 500


    user = user_from_email(
        role,
        email
    )


    if not user:

        return render_template(
            "forgot-password.html",
            role=role,
            success=(
                "If that email is registered "
                "for the selected account type, "
                "a reset link has been sent."
            )
        )


    token = secrets.token_urlsafe(
        32
    )


    expires = (
        datetime.now()
        + timedelta(
            minutes=RESET_EXPIRY_MINUTES
        )
    )


    conn = get_db_connection()

    cur = conn.cursor()


    try:

        cur.execute(
            """
            UPDATE password_resets
            SET used=1
            WHERE
                email=%s
                AND user_type=%s
                AND used=0
            """,
            (
                email,
                role
            )
        )


        cur.execute(
            """
            INSERT INTO password_resets
            (
                email,
                user_type,
                token,
                expires_at,
                used
            )
            VALUES
            (
                %s,
                %s,
                %s,
                %s,
                0
            )
            """,
            (
                email,
                role,
                token,
                expires
            )
        )


        conn.commit()


    finally:

        cur.close()

        conn.close()


    link = url_for(
        "reset_password",
        token=token,
        _external=True
    )


    body = f"""
Hello {user.get('name', '')},

A SmartClean password reset was requested for your
{ROLE_TABLES[role]['role_name']} account.

Open the link below within
{RESET_EXPIRY_MINUTES} minutes to create a new password:

{link}

If you did not request this password reset,
you can safely ignore this email.

Regards,
SmartClean Security Team
"""


    try:

        send_email(
            email,
            "SmartClean Password Reset",
            body
        )


    except Exception as e:

        return render_template(
            "forgot-password.html",
            role=role,
            error=(
                "Email could not be sent. "
                "Check SMTP settings. "
                f"({e})"
            )
        )


    return render_template(
        "forgot-password.html",
        role=role,
        success=(
            "Reset link sent to your "
            "registered email address. "
            "Check your inbox."
        )
    )


# ============================================================
# RESET PASSWORD
# ============================================================

@app.route(
    "/reset-password/<token>",
    methods=["GET", "POST"]
)
def reset_password(token):

    try:
        ensure_password_resets_table()
    except Exception as e:
        return render_template(
            "reset-password.html",
            error=(
                "Unable to prepare password reset. "
                f"({e})"
            )
        ), 500

    conn = get_db_connection()

    cur = conn.cursor(
        dictionary=True
    )


    try:

        cur.execute(
            """
            SELECT *
            FROM password_resets
            WHERE
                token=%s
                AND used=0
                AND expires_at > NOW()
            """,
            (token,)
        )


        reset = cur.fetchone()


        if not reset:

            return render_template(
                "reset-password.html",
                error=(
                    "This reset link is invalid, "
                    "expired, or already used."
                )
            ), 400


        role = reset["user_type"]


        cfg = ROLE_TABLES[role]


        cur.execute(
            f"""
            SELECT *
            FROM {cfg["table"]}
            WHERE email=%s
            """,
            (reset["email"],)
        )


        user = cur.fetchone()


        if not user:

            return render_template(
                "reset-password.html",
                error="Account no longer exists."
            ), 400


        if request.method == "GET":

            return render_template(
                "reset-password.html",
                token=token,
                email=reset["email"]
            )


        new_password = request.form.get(
            "new_password",
            ""
        )


        confirm_password = request.form.get(
            "confirm_password",
            ""
        )


        if new_password != confirm_password:

            return render_template(
                "reset-password.html",
                token=token,
                email=reset["email"],
                error="Passwords do not match."
            ), 400


        if not validate_password(
            new_password
        ):

            return render_template(
                "reset-password.html",
                token=token,
                email=reset["email"],
                error=(
                    "Password must be at least "
                    "6 characters and contain "
                    "an uppercase letter and number."
                )
            ), 400


        hashed_password = (
            generate_password_hash(
                new_password
            )
        )


        cur.execute(
            f"""
            UPDATE {cfg["table"]}
            SET password=%s
            WHERE {cfg["id"]}=%s
            """,
            (
                hashed_password,
                user[cfg["id"]]
            )
        )


        cur.execute(
            """
            UPDATE password_resets
            SET used=1
            WHERE reset_id=%s
            """,
            (reset["reset_id"],)
        )


        conn.commit()


        return render_template(
            "reset-password.html",
            success=(
                "Your password has been "
                "reset successfully. "
                "You can now log in."
            )
        )


    finally:

        cur.close()

        conn.close()


# ============================================================
# CHANGE PASSWORD
# ============================================================

@app.route(
    "/api/change-password",
    methods=["POST"]
)
def api_change_password():

    if not session.get("role"):

        return safe_json_error(
            "Please log in first.",
            401
        )


    data = (
        request.get_json(
            silent=True
        )
        or request.form
    )


    old_password = data.get(
        "old_password",
        ""
    )


    new_password = data.get(
        "new_password",
        ""
    )


    confirm_password = data.get(
        "confirm_password",
        ""
    )


    if new_password != confirm_password:

        return safe_json_error(
            "New passwords do not match."
        )


    if not validate_password(
        new_password
    ):

        return safe_json_error(
            (
                "Password must be at least "
                "6 characters and contain "
                "an uppercase letter and number."
            )
        )


    role = session["role"]


    user = current_user()


    if not user:

        return safe_json_error(
            "User session expired.",
            401
        )


    cfg = ROLE_TABLES[role]


    if not password_matches(
        user["password"],
        old_password
    ):

        return safe_json_error(
            "Current password is incorrect.",
            401
        )


    conn = get_db_connection()

    cur = conn.cursor()


    try:

        cur.execute(
            f"""
            UPDATE {cfg["table"]}
            SET password=%s
            WHERE {cfg["id"]}=%s
            """,
            (
                generate_password_hash(
                    new_password
                ),
                user[cfg["id"]]
            )
        )


        conn.commit()


    finally:

        cur.close()

        conn.close()


    return jsonify(
        {
            "success": True,
            "message":
                "Password updated successfully."
        }
    )


# ============================================================
# PROFILE UPDATE API
# ============================================================

@app.route(
    "/api/profile/update",
    methods=["POST"]
)
def api_profile_update():

    if not session.get("role"):

        return safe_json_error(
            "Please log in first.",
            401
        )


    role = session["role"]


    if role not in ROLE_TABLES:

        return safe_json_error(
            "Invalid user role.",
            400
        )


    return update_profile(
        role,
        json_response=True
    )


# ============================================================
# PROFILE UPDATE
# ============================================================

def update_profile(
    role,
    json_response=False
):

    # --------------------------------------------------------
    # CHECK ROLE
    # --------------------------------------------------------

    if role not in ROLE_TABLES:

        if json_response:

            return safe_json_error(
                "Invalid user role.",
                400
            )


        return redirect(
            url_for("login")
        )


    # --------------------------------------------------------
    # GET CURRENT USER
    # --------------------------------------------------------

    user = current_user()


    if not user:

        if json_response:

            return safe_json_error(
                "User session expired. Please log in again.",
                401
            )


        return redirect(
            url_for(
                f"{role}_login"
            )
        )


    cfg = ROLE_TABLES[role]


    # --------------------------------------------------------
    # READ JSON OR FORM DATA
    # --------------------------------------------------------

    if request.is_json:

        data = (
            request.get_json(
                silent=True
            )
            or {}
        )

    else:

        data = request.form


    # --------------------------------------------------------
    # READ VALUES
    # --------------------------------------------------------

    name = str(
        data.get(
            "name",
            ""
        )
    ).strip()


    email = str(
        data.get(
            "email",
            ""
        )
    ).strip()


    phone = str(
        data.get(
            "phone",
            ""
        )
    ).strip()


    address = str(
        data.get(
            "address",
            ""
        )
    ).strip()


    # --------------------------------------------------------
    # NAME VALIDATION
    # --------------------------------------------------------

    if not name:

        if json_response:

            return safe_json_error(
                "Name cannot be empty.",
                400
            )


        return render_template(
            f"{role}-profile.html",
            user=current_user(),
            error="Name cannot be empty."
        ), 400


    # --------------------------------------------------------
    # EMAIL VALIDATION
    # --------------------------------------------------------

    if not email:

        if json_response:

            return safe_json_error(
                "Email cannot be empty.",
                400
            )


        return render_template(
            f"{role}-profile.html",
            user=current_user(),
            error="Email cannot be empty."
        ), 400


    email_pattern = (
        r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
    )


    if not re.match(
        email_pattern,
        email
    ):

        if json_response:

            return safe_json_error(
                "Please enter a valid email address.",
                400
            )


        return render_template(
            f"{role}-profile.html",
            user=current_user(),
            error=(
                "Please enter a valid email address."
            )
        ), 400


    # --------------------------------------------------------
    # PHONE VALIDATION
    # --------------------------------------------------------

    if phone:

        if not phone.isdigit():

            if json_response:

                return safe_json_error(
                    "Phone number must contain only digits.",
                    400
                )


            return render_template(
                f"{role}-profile.html",
                user=current_user(),
                error=(
                    "Phone number must contain only digits."
                )
            ), 400


        if len(phone) != 10:

            if json_response:

                return safe_json_error(
                    "Phone number must contain 10 digits.",
                    400
                )


            return render_template(
                f"{role}-profile.html",
                user=current_user(),
                error=(
                    "Phone number must contain 10 digits."
                )
            ), 400


    # --------------------------------------------------------
    # BUILD UPDATE FIELDS
    # --------------------------------------------------------

    fields = []

    values = []


    # NAME

    fields.append(
        "name=%s"
    )

    values.append(
        name
    )


    # EMAIL

    fields.append(
        "email=%s"
    )

    values.append(
        email
    )


    # PHONE

    fields.append(
        "phone=%s"
    )

    values.append(
        phone
    )


    # --------------------------------------------------------
    # CITIZEN-SPECIFIC FIELDS
    # --------------------------------------------------------

    if role == "citizen":

        if "address" in data:

            fields.append(
                "address=%s"
            )

            values.append(
                address
            )


        if "ward_number" in data:

            ward_value = data.get(
                "ward_number"
            )


            try:

                ward_number = int(
                    ward_value
                )


                fields.append(
                    "ward_number=%s"
                )

                values.append(
                    ward_number
                )


            except (
                TypeError,
                ValueError
            ):

                pass


    # --------------------------------------------------------
    # WORKER-SPECIFIC FIELDS
    # --------------------------------------------------------

    elif role == "worker":

        if "address" in data:

            fields.append(
                "address=%s"
            )

            values.append(
                address
            )


        if "status" in data:

            status = str(
                data.get(
                    "status"
                )
            ).strip()


            if status in {
                "Available",
                "Busy",
                "Unavailable"
            }:

                fields.append(
                    "status=%s"
                )

                values.append(
                    status
                )


    # --------------------------------------------------------
    # ADMIN-SPECIFIC FIELDS
    # --------------------------------------------------------

    elif role == "admin":

        if "address" in data:
            fields.append("address=%s")
            values.append(address)


    # --------------------------------------------------------
    # USER ID FOR WHERE CLAUSE
    # --------------------------------------------------------

    values.append(
        user[cfg["id"]]
    )


    # --------------------------------------------------------
    # DATABASE UPDATE
    # --------------------------------------------------------

    conn = None

    cur = None


    try:

        conn = get_db_connection()

        cur = conn.cursor()


        query = f"""
            UPDATE {cfg["table"]}
            SET {", ".join(fields)}
            WHERE {cfg["id"]}=%s
        """


        cur.execute(
            query,
            tuple(values)
        )


        conn.commit()


    except mysql.connector.Error as e:

        if conn:

            conn.rollback()


        message = getattr(
            e,
            "msg",
            str(e)
        )


        if (
            "Duplicate entry"
            in message
            and "email"
            in message.lower()
        ):

            message = (
                "This email address is already "
                "registered with another account."
            )


        elif (
            "Duplicate entry"
            in message
            and "phone"
            in message.lower()
        ):

            message = (
                "This phone number is already "
                "registered with another account."
            )


        if json_response:

            return safe_json_error(
                message,
                400
            )


        return render_template(
            f"{role}-profile.html",
            user=current_user(),
            error=message
        ), 400


    finally:

        if cur:

            cur.close()


        if conn:

            conn.close()


    # --------------------------------------------------------
    # GET UPDATED USER FROM DATABASE
    # --------------------------------------------------------

    updated_user = current_user()


    # --------------------------------------------------------
    # JSON RESPONSE
    # --------------------------------------------------------

    if json_response:

        return jsonify(
            {
                "success": True,
                "message":
                    "Profile updated successfully!",
                "user":
                    updated_user
            }
        )


    # --------------------------------------------------------
    # NORMAL FORM RESPONSE
    # --------------------------------------------------------

    return redirect(
        url_for(
            f"{role}_profile"
        )
    )


# ============================================================
# LOGOUT
# ============================================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect(
        url_for("login")
    )


@app.route("/worker-logout")
def worker_logout():

    session.clear()

    return redirect(
        url_for("worker_login")
    )


@app.route("/admin-logout")
def admin_logout():

    session.clear()

    return redirect(
        url_for("admin_login")
    )


# ============================================================
# DATABASE ERROR HANDLER
# ============================================================

@app.errorhandler(
    mysql.connector.Error
)
def db_error(error):

    return render_template(
        "login.html",
        error=(
            "Database connection error: "
            f"{getattr(error, 'msg', str(error))}"
        )
    ), 500


# ============================================================
# HEALTH CHECK
# ============================================================

@app.route("/health")
def health():
    return jsonify({"status": "ok", "service": "SmartClean"})


# ============================================================
# RUN APPLICATION
# ============================================================

if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=int(
            os.getenv(
                "PORT",
                "5000"
            )
        ),
        debug=os.getenv("FLASK_DEBUG", "false").lower() == "true"
    )


